#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: lla ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zospm=`whence zospm`
zospmdir=${zospm%/*} 
zospmroot=${zospmdir%/*}

cat << EOF >${script}
#!/bin/sh
export PRODUCT_CODE="${PRODUCT_CODE}"
export PATH=${zospmdir}:\$PATH
. zospmsetswenv eqae20
. \$ZOSPM_REPOROOT/zospm-eqa/eqafuncs

datasets="\${ZOSPM_TGT_HLQ}EQAE20.SEQAMOD"
if  \`supportsMFI "\$PRODUCT_CODE"\`; then
	datasets="\${datasets} \${ZOSPM_TGT_HLQ}EQAE20.SEQABMOD"
fi
llregistrar eqae20 ${verb} "\${datasets}"
exit \$?
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
