#!/bin/sh
#set -x

if ! [ $# -eq 2 ]; then
	echo "Syntax: dbgmgr_comm ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zospm=`whence zospm`
zospmdir=${zospm%/*} 
zospmroot=${zospmdir%/*}

cat << EOF >${script}
#!/bin/sh
export PATH=${zospmdir}:\$PATH
. zospmsetswenv eqae20
. \$ZOSPM_REPOROOT/zospm-eqa/eqafuncs
export PRODUCT_CODE="$PRODUCT_CODE"

if ! \`supportsDebugManager "\$PRODUCT_CODE"\`; then
	exit 0
fi
sp=\`secmgr\`
if [ "\${sp}" != "RCVT" ]; then
	echo "Security product support for \${sp} not implemented yet" >&2
	exit 16
fi

EOF

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >>${script}

	#MSF TBD
	exit 0
EOF

else 
	cat << EOF >>${script}
	#MSF TBD

	exit 0
EOF
fi

exit 0
