#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: ivp ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zospm=`whence zospm`
zospmdir=${zospm%/*} 
zospmroot=${zospmdir%/*}

cat << EOF >${script}
	#!/bin/sh
	#set -x
	export PATH=${zospmdir}:\$PATH
	. zospmsetenv
EOF

if [ "${verb}" = "DISABLE" ]; then
	cat << EOF >>${script}
	# No code required to 'undo' IVP
	exit 0
EOF

else # ENABLE
	cat << EOF >>${script}
	\${ZOSPM_REPOROOT}/zospm-eqa/eqae20/update/ivp
	exit \$?
EOF

fi

if [ $? -gt 0 ]; then
	echo "Unable to create EQAE20 Update script: ${script}." >&2
	exit 16
fi

chmod u+x "${script}"
exit 0
