#!/bin/sh
#set -x
. zospmsetenv

props="${ZOSPM_WORKROOT}/order/eqae20order.json"
zospmpropse eqae20 order "${props}"

eqaRoot="${ZOSPM_WORKROOT}/config/eqae20"
mkdir -p "${eqaRoot}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "Unable to create configuration directory: ${eqaRoot}"
	exit $rc
fi

cd "${mydir}/generate"
steps=`echo *`
cd $OLDPWD
for step in ${steps}; do
	script="${eqaRoot}/${step}.sh"
	"${mydir}/generate/${step}" ENABLE "${script}"
	if [ $? -gt 0 ]; then
		exit $?
	fi
done

exit 0
